<?php /** @var $block \Pyxl\Pixels\Block\Core */ ?>
<?php if ($p_id = $block->getPinterestHelper()->getTagId()): ?>
	<!-- Pinterest Pixel Base Code -->
	<script type="text/javascript">
        !function(e){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(
            Array.prototype.slice.call(arguments))};var
            n=window.pintrk;n.queue=[],n.version="3.0";var
            t=document.createElement("script");t.async=!0,t.src=e;var
            r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(t,r)}}("https://s.pinimg.com/ct/core.js");
        pintrk('load', <?php echo $p_id ?>​);
        pintrk('page');
	</script>
	<noscript>
		<img height="1" width="1" style="display:none;" alt=""
		     src="https://ct.pinterest.com/v3/?tid=<?php echo $p_id ?>&noscript=1" />
	</noscript>
    <?php if ($block->shouldTrackEvent('pagevisit', 'pinterest')): ?>
	<script>
        pintrk('track', 'pagevisit');
	</script>
	<noscript>
		<img height="1" width="1" style="display:none;" alt=""
		     src="https://ct.pinterest.com/v3/?tid=<?php echo $p_id ?>&event=pagevisit&noscript=1" />
	</noscript>
    <?php endif; ?>
	<!-- End Pinterest Pixel Base Code -->
<?php endif; ?>