<?php /** @var $block \Pyxl\Pixels\Block\Checkout */ ?>
<?php if ($order = $block->getOrder()): ?>
	<script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
	<script type="text/javascript">
        (function() {
            let isMobile = false;
            if ("undefined" !== typeof window.navigator && "undefined" !== typeof window.navigator.userAgent) {
                isMobile = ( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) );
            }
            window.criteo_q = window.criteo_q || [];
            window.criteo_q.push(
                {event: "setAccount", account: <?php echo $block->getCriteoHelper()->getAccountId() ?> },
                {event: "setSiteType", type: (isMobile ? "m" : "d")},
                {event: "setEmail", email: "<?php echo $block->getCustomerEmail() ?>"},
                {
                    event: "trackTransaction",
                    id: "<?php echo $order->getIncrementId() ?>",
                    item: <?php echo $block->getOrderItems('criteo') ?>
                }
            );
        })();
	</script>
<?php endif; ?>