<?php /** @var $block \Pyxl\Pixels\Block\Category */ ?>
<?php if ($block->shouldTrackEvent('viewcategory', 'pinterest') && $block->getCategory()): ?>
	<script>
        pintrk('track', 'viewcategory');
	</script>
	<noscript>
		<img height="1" width="1" style="display:none;" alt=""
		     src="https://ct.pinterest.com/v3/?tid=<?php echo $block->getPinterestHelper()->getAccountId() ?>&event=viewcategory&noscript=1" />
	</noscript>
<?php endif; ?>