<?php /** @var $block \Pyxl\Pixels\Block\Search */ ?>
<?php if ($search = $block->getSearchString()): ?>
	<script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
	<script type="text/javascript">
        (function() {
            let isMobile = false;
            if ("undefined" !== typeof window.navigator && "undefined" !== typeof window.navigator.userAgent) {
                isMobile = ( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) );
            }
            window.criteo_q = window.criteo_q || [];
            window.criteo_q.push(
                {event: "setAccount", account: <?php echo $block->getCriteoHelper()->getAccountId() ?> },
                {event: "setSiteType", type: (isMobile ? "m" : "d")},
                {event: "setEmail", email: "<?php echo $block->getCustomerEmail() ?>"},
                {event: "viewList", item: <?php echo $block->getCriteoItems() ?> }
            );
        })();
	</script>
<?php endif; ?>